# Configuraci贸n de Nixpacks para el entorno de Python

# Proveedor principal: Python
providers = ['python']

# Imagen base para construir
buildImage = 'ghcr.io/railwayapp/nixpacks:latest'

[phases.setup]
# Instalaci贸n de paquetes del sistema necesarios para OpenCV y Python
aptPkgs = [
  'libgl1-mesa-glx',     # Necesaria para OpenCV
  'libglib2.0-0',        # Dependencia requerida por OpenCV
  'gcc'                  # Para compilar extensiones nativas de Python
]

[phases.install]
# Comandos para configurar Python e instalar dependencias
cmds = [
  "python -m venv /app/.venv",                                # Crear el entorno virtual en /app
  "/app/.venv/bin/pip install --upgrade pip setuptools wheel", # Actualizar herramientas esenciales
  "/app/.venv/bin/pip install tensorflow-cpu gunicorn django opencv-python-headless matplotlib pillow" # Instalar dependencias de Python
]

[phases.build]
# No se requieren comandos adicionales para construir la aplicaci贸n
cmds = ["echo 'Build complete'"]

[start]
# Comando para iniciar la aplicaci贸n desde el entorno virtual
cmd = "ls -la /app/.venv && /app/.venv/bin/python -m gunicorn DRD.wsgi:application --bind 0.0.0.0:$PORT"

# Especificar una imagen de runtime ligera
runImage = 'python:3.12-slim'
