# Configuración de Nixpacks para el entorno de Python

# Proveedor principal: Python
providers = ['python']

# Imagen base para construir
buildImage = 'ghcr.io/railwayapp/nixpacks:latest'

[phases.setup]
# Instalación de paquetes del sistema necesarios
aptPkgs = [
  'libgl1-mesa-glx',
  'libglib2.0-0',
  'gcc'
]

[phases.install]
# Configuración de Python e instalación de dependencias
cmds = [
  "/usr/local/bin/python -m ensurepip --upgrade",               # Asegurarse de que pip esté disponible
  "/usr/local/bin/python -m venv /app/.venv",                  # Crear el entorno virtual en /app
  "/app/.venv/bin/pip install --upgrade pip setuptools wheel", # Actualizar herramientas esenciales
  "/app/.venv/bin/pip install tensorflow-cpu gunicorn django opencv-python-headless matplotlib pillow" # Instalar dependencias
]

[phases.build]
# No se requieren comandos adicionales para construir la aplicación
cmds = ["echo 'Build complete'"]

[start]
# Validar que Gunicorn se ejecute correctamente
cmd = "ls -la /app/.venv/bin && /app/.venv/bin/python -m gunicorn DRD.wsgi:application --bind 0.0.0.0:$PORT"

# Imagen ligera para ejecución
runImage = 'python:3.12-slim'
