# Configuración de Nixpacks para el entorno de Python

# Proveedor principal: Python
providers = ['python']

# Imagen base para construir
buildImage = 'ghcr.io/railwayapp/nixpacks:latest'

[phases.setup]
aptPkgs = [
  'libgl1-mesa-glx',
  'libglib2.0-0',
  'gcc'
]

[phases.install]
cmds = [
  "/usr/local/bin/python -m ensurepip --upgrade",
  "/usr/local/bin/python -m venv /app/.venv",
  "/app/.venv/bin/pip install --upgrade pip setuptools wheel",
  "/app/.venv/bin/pip install tensorflow-cpu gunicorn django opencv-python-headless matplotlib pillow"
]

[phases.build]
cmds = ["echo 'Build complete'"]

[start]
cmd = """
ls -la /app/.venv && ls -la /app/.venv/bin && \
echo "Testing Python version:" && /app/.venv/bin/python --version && \
echo "Testing Gunicorn version:" && /app/.venv/bin/gunicorn --version && \
/app/.venv/bin/python -m gunicorn DRD.wsgi:application --bind 0.0.0.0:$PORT
"""
