[build]
# Usa Nixpacks para preparar el entorno y asegurarte de instalar dependencias del sistema
cmd = """
apt-get update && apt-get install -y \
    libgl1-mesa-glx \
    libglib2.0-0 \
    gcc \
    && rm -rf /var/lib/apt/lists/*
"""

[start]
# Crear un entorno virtual, instalar dependencias y ejecutar la aplicación
cmd = """
python -m venv .venv && . .venv/bin/activate \
    && pip install --no-cache-dir django gunicorn tensorflow matplotlib opencv-python pillow \
    && gunicorn DRD.wsgi:application --bind 0.0.0.0:$PORT
"""
