[build]
# Usa Nixpacks como builder
builder = "Nixpacks"

[start]
# Crear entorno virtual, instalar dependencias manualmente y ejecutar la aplicación
cmd = """
    pip install --no-cache-dir tensorflow-cpu gunicorn django opencv-python-headless matplotlib pillow \
    && gunicorn DRD.wsgi:application --bind 0.0.0.0:$PORT
"""

