[build]
# Usa Nixpacks como el builder para instalar dependencias del sistema y preparar el entorno
builder = "Nixpacks"

# Comando personalizado para preparar el entorno
cmd = """
apt-get update && apt-get install -y \
    && python -m venv .venv \
    && . .venv/bin/activate \
    && pip install --upgrade pip setuptools wheel
"""

[start]
# Crear un entorno virtual, instalar dependencias y ejecutar la aplicación
cmd = """
python -m venv .venv && . .venv/bin/activate \
    && pip install --no-cache-dir django gunicorn tensorflow-cpu matplotlib opencv-python-headless pillow \
    && gunicorn DRD.wsgi:application --bind 0.0.0.0:$PORT
"""