# Generated by Django 5.1.4 on 2024-12-16 07:37

import django.db.models.deletion
import uuid
import webserver.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('birth_date', models.DateField()),
                ('medical_history', models.TextField()),
                ('contact', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DiagnosticImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('image', models.ImageField(upload_to=webserver.models.diagnostic_images_upload_to)),
                ('gradcam_image', models.ImageField(blank=True, null=True, upload_to=webserver.models.diagnostic_images_upload_to)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('diagnosis_result', models.TextField(blank=True, null=True)),
                ('consultation_date', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnostic_images', to='webserver.patient')),
            ],
        ),
    ]
