# Generated by Django 5.1.3 on 2024-12-07 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webserver', '0004_alter_diagnosticimage_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosticimage',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
