# Generated by Django 5.1.3 on 2024-12-07 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webserver', '0005_alter_diagnosticimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosticimage',
            name='gradcam_image',
            field=models.ImageField(blank=True, null=True, upload_to='diagnostic_images/'),
        ),
        migrations.AlterField(
            model_name='diagnosticimage',
            name='image',
            field=models.ImageField(upload_to='diagnostic_images/'),
        ),
    ]
