# Generated by Django 5.1.4 on 2024-12-16 02:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webserver', '0008_patient_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosticimage',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='patient',
            name='birth_date',
            field=models.DateField(),
        ),
    ]
