# Generated by Django 5.1.4 on 2024-12-16 06:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webserver', '0009_alter_diagnosticimage_id_alter_patient_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosticimage',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='diagnosticimage',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
