# Generated by Django 5.1.3 on 2024-12-07 05:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webserver', '0002_diagnosticimage_consultation_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnosticimage',
            name='model_used',
        ),
        migrations.AlterField(
            model_name='diagnosticimage',
            name='consultation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='diagnosticimage',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
