# Generated by Django 5.1.3 on 2024-12-07 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webserver', '0003_remove_diagnosticimage_model_used_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosticimage',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
